<?php
include_once('functions/library.php');
$html = new Html_5('Formulario');
$html->body_I();
$html->links('CSS','css/foundation.css');
$html->links('JS','js/modernizr.js');
// Formulario: Datos para Caracterización de Muertes Maternas
echo '<div class="row">';
    // Inicio del Menu Principal
    //$menu = new Menu();
    //$menu->menu_I(); // Imprime el inicio del menu
    $titulo = new Titulo('CENAVIF - Sistema para el Reporte de Reacciones Adversas a Medicamentos','CENAVIF');
    // Inicio del Formulario
    $form = new Formulario('Formulario para el Reporte de Reacciones Adversas a Medicamentos');
    // form_I($method,$action,$name,$onsubmit,$atributo)
    $form->form_I('post','#','formulario','','class="large-12 columns" data-abide="ajax"');
        
        echo '<dl class="tabs vertical" data-tab>';
            echo '<dd class="active"><a href="#panel1">Parte 1</a></dd>';
            echo '<dd><a href="#panel2">Parte 2</a></dd>';
            echo '<dd><a href="#panel3">Parte 3</a></dd>';
            echo '<dd><a href="#panel4">Parte 4</a></dd>';
            echo '<dd><a href="#panel5">Parte 5</a></dd>';
            echo '<dd><a href="#panel6">Parte 6</a></dd>';
            echo '<dd><a href="#panel7">Parte 7</a></dd>';
            echo '<dd><a href="#panel8">Parte 8</a></dd>';
        echo'</dl>';
        
        echo '<div class="tabs-content vertical">';
            
            echo '<div class="large-12 columns content active" id="panel1">';
            // Parte 1
            echo '<fieldset><legend>Parte 1 - Información del Reporte</legend>';                 
                
                echo '<fieldset class="large-12"><legend>Información del Reporte – Caso Standard</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-3 columns">';
                            $form->label('part1[]','Id  del reporte','');
                            //input($name,$type,$placeholder,$atributo)
                            $form->input('part1[]','text','','value="0001" readonly');
                        echo '</div>';
                        
                        echo '<div class="large-9 columns">';
                            $form->label('','Primera Fecha de Recepción','');
                            echo '<div class="row">';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','date');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','month');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','year');
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';              
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-6 columns">';
                            $form->label('part1[]','Título del Reporte','');
                            //input($name,$type,$placeholder,$atributo)
                            $form->input('part1[]','text','','required');
                        echo '</div>';
                        
                        echo '<div class="large-6 columns">';
                            $form->label('part1[]','Tipo de Reporte','');
                            //input($name,$type,$placeholder,$atributo)
                            $form->input('part1[]','text','','required');
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Serio','');                                                   
                            $form->radio('part1[]','SI','','');
                            $form->radio('part1[]','NO','','');                                   
                            echo '<hr>';
                        echo '</div>';
                        
                        echo '<div class="large-12 columns">';
                            $form->label('','Razón de Gravedad',''); 
                            echo '<div class="large-6 columns">';
                                echo '<div class="large-12 ">'; $form->checkbox('part1[]','Muerte','',''); echo '</div>';
                                echo '<div class="large-12 ">'; $form->checkbox('part1[]','Hospitalización Prolongada','',''); echo '</div>';
                                echo '<div class="large-12 ">'; $form->checkbox('part1[]','Anomalía Congénita','',''); echo '</div>';         
                            echo '</div>';       
                            echo '<div class="large-6 columns">';   
                                echo '<div class="large-12 ">'; $form->checkbox('part1[]','Amenaza de Vida','',''); echo '</div>';
                                echo '<div class="large-12 ">'; $form->checkbox('part1[]','Discapacidad','',''); echo '</div>';
                                echo '<div class="large-12 ">'; $form->checkbox('part1[]','Otra Condición Médica Importante','',''); echo '</div>';    
                            echo '</div>';
                            echo '<hr>';                         
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-6 columns">';
                            $form->label('part1[]','País de Ocurrencia','');                            
                            $form->select('part1[]','required','');
                        echo '</div>';
                        
                        echo '<div class="large-6 columns">';
                            $form->label('part1[]','País de Origen Primario','');                            
                            $form->select('part1[]','required','');
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Este caso cumple con los criterios locales para un reporte expeditivo ','');                                                   
                            $form->radio('part1[]','SI','','');
                            $form->radio('part1[]','NO','','');                                   
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-6 columns">';
                            $form->label('','Documentos Adicionales','');                                                   
                            $form->radio('part1[]','SI','','');
                            $form->radio('part1[]','NO','','');                                   
                        echo '</div>';
                        echo '<div class="large-6 columns">';
                            $form->label('','Fue el Caso Medicamente Confirmado','');                                                   
                            $form->radio('part1[]','SI','','');
                            $form->radio('part1[]','NO','','');                                   
                        echo '</div>';
                    echo '</div>';
                echo '</fieldset>'; // Fin del Fieldset Información del Reporte – Caso Standard  
                echo '<fieldset class="large-12"><legend>Información del Remitente</legend>';
                    echo '<div class="large-12 columns">';
                            $form->label('','Razón de Gravedad',''); 
                            echo '<div class="large-6 columns">';
                                echo '<div class="large-12 ">'; $form->radio('part1[]','Muerte','',''); echo '</div>';
                                echo '<div class="large-12 ">'; $form->radio('part1[]','Hospitalización Prolongada','',''); echo '</div>';
                                echo '<div class="large-12 ">'; $form->radio('part1[]','Anomalía Congénita','',''); echo '</div>';         
                            echo '</div>';       
                            echo '<div class="large-6 columns">';   
                                echo '<div class="large-12 ">'; $form->radio('part1[]','Amenaza de Vida','',''); echo '</div>';
                                echo '<div class="large-12 ">'; $form->radio('part1[]','Discapacidad','',''); echo '</div>';
                                echo '<div class="large-12 ">'; $form->radio('part1[]','Otra Condición Médica Importante','',''); echo '</div>';    
                            echo '</div>';
                            echo '<hr>';
                    echo '</div>';
                    echo '<div class="large-12 columns">';
                            $form->label('','Primera Fecha de Recepción','');
                            echo '<div class="row">';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','date');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','month');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','year');
                                echo '</div>';
                            echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Otros Identificadores de caso en transmisiones previas ','');
                            echo '<button class="button secondary tiny" type="button">Agregar Nuevo Identificador</button>';        
                        echo '</div>';
                        echo '<div class="large-12 columns">';
                            echo '<fieldset class="large-12 columns"><legend>Número Único Mundial</legend>';
                                echo '<div class="large-6 columns">';
                                $form->label('part1[]','Número de la Autoridad','');
                                //input($name,$type,$placeholder,$atributo)
                                $form->input('part1[]','text','','required');
                                echo '</div>';
                                echo '<div class="large-6 columns">';
                                $form->label('part1[]','Número del Laboratorio','');
                                //input($name,$type,$placeholder,$atributo)
                                $form->input('part1[]','text','','required');
                                echo '</div>';
                            echo '</fieldset>';
                        echo '</div>';                       
                    echo '</div>';
                echo '</fieldset>'; // Fin del Fieldset Información del Remitente
                echo '<fieldset class="large-12"><legend>Información Acerca del Notificador</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-5 columns">';
                            //$form->label('part1[]','','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                        echo '<div class="large-7 columns">';
                            echo '<ul class="button-group radius">';
                                echo '<li><button type="button" class="button secondary tiny">Encontrar Fuente Primaria</button></li>';
                                echo '<li><button type="button" class="button secondary tiny">Guardar Fuente Primaria</button></li>';
                            echo '</ul>';     
                        echo '</div>';                                              
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','Primer Nombre','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','Apellido','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','Institución','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';                                              
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','Departamento','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','Domicilio','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','Estado','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';                                              
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','Código Postal','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','Ciudad','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','Teléfono','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','Fax','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','E-mail','');
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                        echo '<div class="large-4 columns">';
                            $form->label('part1[]','País del Notificador','');
                            $form->select('part1[]','required','');  
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                                $form->label('','Calificación del Notificador',''); 
                                echo '<div class="large-6 columns">';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Médico','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Abogado','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Consumidor u otro Profesional','',''); echo '</div>';         
                                echo '</div>';       
                                echo '<div class="large-6 columns">';   
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Farmacéutico','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Otro Profesional de la Salud','',''); echo '</div>';   
                                echo '</div>';
                                echo '<hr>';
                        echo '</div>';                        
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">'; 
                            $form->label('part1[]','Referencia del Literatura','');
                            $form->input('part1[]','text','','required');   
                        echo '</div>';
                    echo '</div>';                                                                
                echo '</fieldset>'; // Fin del Fieldset Información Acerca del Notificador
            echo '</fieldset>'; 
            echo '</div>';
            
            echo '<div class="content large-12 columns" id="panel2">';
            // Parte 2
            echo '<fieldset><legend>Parte 2 - Paciente</legend>';
                echo '<fieldset><legend>Características del Paciente</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Primera Fecha de Recepción','');
                                echo '<div class="row">';
                                    echo '<div class="large-4 columns">';
                                        $form->select('part1[]','required','date');
                                    echo '</div>';
                                    echo '<div class="large-4 columns">';
                                        $form->select('part1[]','required','month');
                                    echo '</div>';
                                    echo '<div class="large-4 columns">';
                                        $form->select('part1[]','required','year');
                                    echo '</div>';
                                echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-6 columns">';
                            $form->label('','Edad al Comienzo','');  
                            echo '<div class="row">';                 
                                echo '<div class="large-6 columns">';                                
                                    $form->input('part1[]','text','','required');    
                                echo '</div>';                            
                                echo '<div class="large-6 columns">';
                                    $form->select('part1[]','required','');   
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="large-6 columns">';
                            $form->label('','Grupo Etareo','');  
                            $form->select('part1[]','required','');   
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';                        
                        echo '<div class="large-4 columns">';
                            $form->label('','Iniciales del Paciente','');  
                            $form->input('part1[]','text','','required');    
                        echo '</div>';
                        echo '<div class="large-4 columns">';
                            $form->label('','Peso (kg)','');  
                            $form->input('part1[]','text','','required');       
                        echo '</div>';
                        echo '<div class="large-4 columns">';
                            $form->label('','Altura (cm)','');  
                            $form->input('part1[]','text','','required'); 
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';   
                        echo '<div class="large-12 columns">';
                            $form->label('','Sexo','');                                                   
                            $form->radio('part1[]','Masculino','','');
                            $form->radio('part1[]','Femenino','','');
                            $form->radio('part1[]','Desconocido','','');                                   
                        echo '</div>'; 
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';                            
                            echo '<button class="button secondary tiny" type="button">Información Adicional del Paciente</button>';        
                        echo '</div>'; 
                    echo '</div>';                                  
                echo '</fieldset>'; // Fin del Fieldset Características del Paciente
                echo '<fieldset><legend>Información Relacionada con la Muerte</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Primera Fecha de Recepción','');
                                echo '<div class="row">';
                                    echo '<div class="large-4 columns">';
                                        $form->select('part1[]','required','date');
                                    echo '</div>';
                                    echo '<div class="large-4 columns">';
                                        $form->select('part1[]','required','month');
                                    echo '</div>';
                                    echo '<div class="large-4 columns">';
                                        $form->select('part1[]','required','year');
                                    echo '</div>';
                                echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Causa de Muerte','');
                            echo '<div class="row">';
                                echo '<div class="large-4 columns">';
                                    $form->input('part1[]','text','','required'); 
                                echo '</div>';
                                echo '<div class="large-2 columns">';   
                                    $form->checkbox('part1[]','Código','','');
                                echo '</div>';
                                echo '<div class="large-6 columns">';
                                    echo '<button class="button secondary tiny" type="button">Información Adicional del Paciente</button>';
                                echo '</div>';
                            echo '</div>';                              
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';   
                        echo '<div class="large-12 columns">';
                            $form->label('','Fue Realizada una Autopsia','');                                                   
                            $form->radio('part1[]','SI','','');
                            $form->radio('part1[]','NO','','');
                            $form->radio('part1[]','Desconocido','','');                                   
                        echo '</div>'; 
                    echo '</div>';
                    echo '<div class="row">';   
                        echo '<div class="large-12 columns">';
                            $form->label('','Fue Realizada una Autopsia','');                                                   
                            // textarea($name,$placeholder,$atributo)
                            $form->textarea('part1[]','','required');
                        echo '</div>'; 
                    echo '</div>';
                echo '</fieldset>'; // Fin del Fieldset Información Relacionada con la Muerte
            echo '</fieldset>';
            echo '</div>';
            // Parte 3
            echo '<div class="content large-12" id="panel3">';
            echo '<fieldset><legend>Parte 3 - Análisis y Procedimientos</legend>';
                echo '<fieldset><legend>Resultados de Análisis y Procedimientos</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('part1[]','Resultados de Análisis y Procedimientos','');                                                                     // textarea($name,$placeholder,$atributo)
                            $form->textarea('part1[]','','required');
                        echo '</div>';    
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-6 columns">';
                            echo '<button class="button secondary tiny" type="button">Agregar Nuevo Análisis</button>';
                        echo '</div>';    
                    echo '</div>';
                echo '</fieldset>'; // Fin del Fieldset Análisis y Procedimientos
                echo '<fieldset><legend>Análisis</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-5 columns">';
                            $form->label('part1[]','Tipo de Análisis','');                                                                                             $form->input('part1[]','text','','required'); 
                        echo '</div>';
                        echo '<div class="large-5 columns">';
                            $form->label('part1[]','Tipo de Análisis (texto libre)','');                                                                               $form->input('part1[]','text','','required'); 
                        echo '</div>';  
                        echo '<div class="large-2 columns">';
                            echo '<br>';
                            echo '<button class="button secondary tiny" type="button">Suprimir</button>';
                        echo '</div>';  
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->checkbox('part1[]','Usar Valores por Defecto','','');
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-4 columns">';
                            $form->label('','Rango bajo/alto','');
                            echo '<div class="row">';
                                echo '<div class="large-6 columns">';
                                    $form->input('part1[]','text','','required'); 
                                echo '</div>';
                                echo '<div class="large-6 columns">';
                                    $form->input('part1[]','text','','required'); 
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="large-3 columns">';
                            $form->label('','Unidad del Análisis','');
                            $form->select('part1[]','required','');
                        echo '</div>';
                        echo '<div class="large-5 columns">';
                            $form->label('','Unidad del análisis (texto libre)','');
                            $form->input('part1[]','text','','required'); 
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Más información disponible','');                                                   
                            $form->radio('part1[]','SI','','');
                            $form->radio('part1[]','NO','','');
                            $form->radio('part1[]','Desconocido','','');
                            echo '<button class="button secondary tiny" type="button">Limpiar</button>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            echo '<fieldset><legend>Resultados</legend>';                            
                                echo '<div class="row">';
                                    echo '<div class="large-6 columns">';
                                        $form->label('','Fecha',''); 
                                        echo '<div class="row">';
                                            echo '<div class="large-4 columns">';
                                                $form->select('part1[]','required','date');
                                            echo '</div>';
                                            echo '<div class="large-4 columns">';
                                                $form->select('part1[]','required','month');
                                            echo '</div>';
                                            echo '<div class="large-4 columns">';
                                                $form->select('part1[]','required','year');
                                            echo '</div>';
                                        echo '</div>';
                                    echo '</div>';
                                    echo '<div class="large-4 columns">';  
                                        $form->label('part1[]','Fecha',''); 
                                        $form->input('part1[]','text','','required');                                 
                                    echo '</div>';
                                    echo '<div class="large-2 columns">';  
                                        echo '<br>';
                                        echo '<button class="button alert tiny" type="button">Eliminar</button>';                     
                                    echo '</div>';
                                echo '</div>';                                                                                            
                            echo '</fieldset>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-4 columns">';
                            echo '<br>';
                            echo '<button class="button secondary tiny" type="button">Agregar Nuevo Resultado</button>';
                        echo '</div>';
                        echo '<div class="large-8 columns">';
                            $form->label('part1[]','Número de Resultados a ser Agregados ',''); 
                            echo '<div class="row">';
                                echo '<div class="large-3 columns">';
                                    $form->input('part1[]','text','','required'); 
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                echo '</fieldset>'; // Fin del Fieldset Análisis
            echo '</fieldset>';
            echo '</div>';
            echo '<div class="content large-12 columns" id="panel4">';
            // Parte 4
            echo '<fieldset><legend>Parte 4 - Historia Clínica Relevante</legend>';
                echo '<fieldset><legend>Historia Clínica Relevante – Texto Libre</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('part1[]','Historia Clínica Relevante',''); 
                            // textarea($name,$placeholder,$atributo)
                            $form->textarea('part1[]','','required');
                        echo '</div>'; 
                        echo '<div class="large-12 columns">';
                            echo '<button class="button secondary tiny" type="button">Agregar Historia Clínica Relevante</button>';
                        echo '</div>';                     
                    echo '</div>';
                echo '</fieldset>';
                echo '<fieldset><legend>Historia Clínica Relevante</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-4 columns">';
                            $form->input('part1[]','text','','required');
                        echo '</div>';
                        echo '<div class="large-8 columns">';
                           $form->checkbox('part1[]','Código','','');
                           echo '<button class="button secondary tiny" type="button">Buscar Término</button>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-7 columns">';
                            $form->label('','Contínuo','');                                                   
                            $form->radio('part1[]','SI','','');
                            $form->radio('part1[]','NO','','');
                            $form->radio('part1[]','Desconocido','','');
                            echo '<button class="button secondary tiny" type="button">Limpiar</button>';
                        echo '</div>';
                        echo '<div class="large-5 columns">';
                            $form->label('','Fecha de Comienzo',''); 
                            echo '<div class="row">';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','date');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','month');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','year');
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('part1[]','Comentario',''); 
                            // textarea($name,$placeholder,$atributo)
                            $form->textarea('part1[]','','required');
                        echo '</div>';
                    echo '</div>';
                echo '</fieldset>';                
            echo '</fieldset>';
            echo '</div>';
            echo '<div class="content large-12 columns" id="panel5">';
            // Parte 5
            echo '<fieldset><legend>Parte 5 - Tratamiento Médico Relevante Previo</legend>';
                echo '<fieldset><legend>Tratamiento Previo Médico Relevante</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            echo '<button class="button secondary tiny" type="button">Agregar Tratamiento Médico Previo</button>';
                        echo '</div>';
                    echo '</div>';
                echo '</fieldset>'; 
                echo '<fieldset><legend>Tratamiento</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';                                
                            $form->label('part1[]','Nombre del Medicamento',''); 
                            $form->input('part1[]','text','','required');                                 
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-6 columns">';
                            $form->label('','Fecha de comienzo',''); 
                            echo '<div class="row">';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','date');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','month');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','year');
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="large-6 columns">';
                            $form->label('','Fecha de Finalización',''); 
                            echo '<div class="row">';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','date');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','month');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','year');
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('part1[]','Indicación','');
                            echo '<div class="row">';
                                echo '<div class="large-4 columns">';
                                    $form->input('part1[]','text','','required');
                                echo '</div>';
                                echo '<div class="large-8 columns">';
                                   $form->checkbox('part1[]','Código','','');
                                   echo '<button class="button secondary tiny" type="button">Buscar Término</button>';
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('part1[]','Reacción','');
                            echo '<div class="row">';
                                echo '<div class="large-2 columns">';
                                    $form->select('part1[]','required','');
                                echo '</div>';
                                echo '<div class="large-2 columns">';
                                    $form->select('part1[]','required','');
                                echo '</div>';
                                echo '<div class="large-3 columns">';
                                    $form->input('part1[]','text','','required');
                                echo '</div>';
                                echo '<div class="large-2 columns">';
                                    $form->select('part1[]','required','');
                                echo '</div>';
                                echo '<div class="large-3 columns">';
                                    echo '<button class="button secondary tiny" type="button">Buscar Término</button>';
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';                    
                echo '</fieldset>';
            echo '</fieldset>';
            echo '</div>';
            echo '<div class="large-12 columns content" id="panel6">';
            // Parte 6
            echo '<fieldset><legend>Parte 6 - Reacciones</legend>';
                echo '<fieldset><legend>Reaccion(es) / Evento(s)</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('part1[]','Comentarios del Notificador','');
                            // textarea($name,$placeholder,$atributo)
                            $form->textarea('part1[]','','required');
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            echo '<button class="button secondary tiny" type="button">Agregar Nueva Reacción</button>';
                        echo '</div>';
                    echo '</div>';
                echo '</fieldset>';
                echo '<fieldset><legend>Reacción / Evento ()</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('part1[]','Término de la Reacción','');
                            echo '<div class="row">';
                                echo '<div class="large-2 columns">';
                                    $form->select('part1[]','required','');
                                echo '</div>';
                                echo '<div class="large-2 columns">';
                                    $form->select('part1[]','required','');
                                echo '</div>';
                                echo '<div class="large-3 columns">';
                                    $form->input('part1[]','text','','required');
                                echo '</div>';
                                echo '<div class="large-3 columns">';
                                    $form->select('part1[]','required','');
                                echo '</div>';
                                echo '<div class="large-2 columns">';
                                    echo '<button class="button secondary tiny" type="button">Buscar</button>';
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            echo '<button class="button secondary tiny" type="button">Sugerir Nuevo Término WHO-ART</button>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('part1[]','Reacción/evento tal como fue reportado por la fuente primaria','');
                            // textarea($name,$placeholder,$atributo)
                            $form->textarea('part1[]','','required');
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Fecha de Comienzo',''); 
                            echo '<div class="row">';
                                echo '<div class="large-8 columns">';
                                    echo '<div class="row">';
                                        echo '<div class="large-4 columns">';
                                            $form->select('part1[]','required','date');
                                        echo '</div>';
                                        echo '<div class="large-4 columns">';
                                            $form->select('part1[]','required','month');
                                        echo '</div>';
                                        echo '<div class="large-4 columns">';
                                            $form->select('part1[]','required','year');
                                        echo '</div>'; 
                                    echo '</div>'; 
                                echo '</div>';                                     
                                echo '<div class="large-4 columns">';                                    
                                    echo '<div class="row">';
                                        echo '<div class="large-2 columns">';
                                            echo '<p class="text-center">:</p>';
                                        echo '</div>'; 
                                        echo '<div class="large-5 columns">';
                                            $form->select('part1[]','required','hour');
                                        echo '</div>';
                                        echo '<div class="large-5 columns">';
                                            $form->select('part1[]','required','minute');
                                        echo '</div>';   
                                    echo '</div>';      
                                echo '</div>';                                
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Fecha de Finalización',''); 
                            echo '<div class="row">';
                                echo '<div class="large-8 columns">';
                                    echo '<div class="row">';
                                        echo '<div class="large-4 columns">';
                                            $form->select('part1[]','required','date');
                                        echo '</div>';
                                        echo '<div class="large-4 columns">';
                                            $form->select('part1[]','required','month');
                                        echo '</div>';
                                        echo '<div class="large-4 columns">';
                                            $form->select('part1[]','required','year');
                                        echo '</div>'; 
                                    echo '</div>'; 
                                echo '</div>';                                     
                                echo '<div class="large-4 columns">';                                    
                                    echo '<div class="row">';
                                        echo '<div class="large-2 columns">';
                                            echo '<p class="text-center">:</p>';
                                        echo '</div>'; 
                                        echo '<div class="large-5 columns">';
                                            $form->select('part1[]','required','hour');
                                        echo '</div>';
                                        echo '<div class="large-5 columns">';
                                            $form->select('part1[]','required','minute');
                                        echo '</div>';   
                                    echo '</div>';      
                                echo '</div>';                                
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Duración',''); 
                            echo '<div class="row">';
                                 echo '<div class="large-5 columns">';  
                                     $form->input('part1[]','text','','required');                              
                                 echo '</div>';
                                 echo '<div class="large-5 columns">';  
                                     $form->select('part1[]','required','');                            
                                 echo '</div>';
                                 echo '<div class="large-2 columns">';  
                                     echo '<button class="button secondary tiny" type="button">Calculadora</button>';           
                                 echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                                $form->label('','Resultado de la Reacción',''); 
                                echo '<div class="large-6 columns">';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Recuperado/Resuelto','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Recuperando/Resolviendo','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Recuperado/Resuelto con Secuela','',''); echo '</div>';         
                                echo '</div>';       
                                echo '<div class="large-6 columns">';   
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','No Recuperado/No Resuelto','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Fatal','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Desconocido','',''); echo '</div>';   
                                echo '</div>';
                                echo '<hr>';
                        echo '</div>';                        
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Resaltado',''); 
                            $form->select('part1[]','required','');                   
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            echo '<button class="button secondary tiny" type="button">Sección de Datos de la Vacuna</button>';                    
                        echo '</div>';
                    echo '</div>';
                echo '</fieldset>';
                echo '<fieldset><legend>Relación entre el(los) Medicamento(s) y la(s) Reaccion(es)</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-10 columns">';
                            $form->select('part1[]','required',''); 
                        echo '</div>';
                        echo '<div class="large-2 columns">';
                            echo '<button class="button alert tiny" type="button">Eliminar</button>';  
                        echo '</div>';
                    echo '</div>';
                echo '</fieldset>';
            echo '</fieldset>';
            echo '</div>';
            echo '<div class="large-12 columns content" id="panel7">';
            // Parte 7
            echo '<fieldset><legend>Parte 7 - Medicamentos</legend>';
                echo '<fieldset><legend>Medicamento Sospechado ()</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Nombre del Medicamento','');
                            echo '<div class="row">';
                                echo '<div class="large-8 columns">';
                                    $form->input('part1[]','text','','required');   
                                echo '</div>'; 
                                echo '<div class="large-4 columns">';
                                    echo '<button class="button secondary tiny" type="button">Buscar Medicamento</button>';   
                                echo '</div>';                            
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Caracterización','');                                                   
                            $form->radio('part1[]','Sospechado','','');
                            $form->radio('part1[]','Interactuado','','');
                            echo '<button class="button secondary tiny" type="button">Modificar a Concomitante</button>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Principio Activo Sospechado','');    
                            $form->select('part1[]','required','');   
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Forma Farmacéutica','');    
                            $form->select('part1[]','required','');   
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Vía de Administración','');    
                            $form->select('part1[]','required','');   
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Indicación','');
                            echo '<div class="row">';
                                echo '<div class="large-5 columns">';
                                    $form->input('part1[]','text','','required');   
                                echo '</div>';
                                echo '<div class="large-2 columns">';
                                    $form->checkbox('part1[]','Código','','');
                                echo '</div>';
                                echo '<div class="large-5 columns">';
                                    echo '<button class="button secondary tiny" type="button">Buscar Término</button>';
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                                $form->label('','Reacción Tomada',''); 
                                echo '<div class="large-6 columns">';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Medicamento Retirado','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Dosis Aumentada','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Desconocido','',''); echo '</div>';         
                                echo '</div>';       
                                echo '<div class="large-6 columns">';   
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Dosis Reducida','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','Dosis No Modificada','',''); echo '</div>';
                                    echo '<div class="large-12 ">'; $form->radio('part1[]','No Aplicable','',''); echo '</div>';   
                                echo '</div>';
                                echo '<hr>';
                        echo '</div>';                        
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                                $form->label('','La Reacción Recurrió luego de la Reexposición',''); 
                                echo '<div class="row">';
                                    echo '<div class="large-12 columns">';
                                        $form->radio('part1[]','Si','','');
                                        $form->radio('part1[]','No','','');
                                        $form->radio('part1[]','Efecto Desconocido','','');
                                        echo '<button class="button secondary tiny" type="button">Buscar Término</button>';
                                    echo '</div>';         
                                echo '</div>';                                                                       
                        echo '</div>';                        
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','El Efecto Adverso está Adecuadamente Descripto',''); 
                            $form->select('part1[]','required','');   
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            echo '<button class="button secondary tiny" type="button">Sección de Datos de la Vacuna</button>';   
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row panel">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Obtener País',''); 
                            $form->select('part1[]','required','');   
                        echo '</div>';
                        echo '<div class="large-6 columns">';
                            $form->label('','Número de Lote',''); 
                            $form->input('part1[]','text','','required');     
                        echo '</div>';
                        echo '<div class="large-6 columns">';
                            $form->label('','Número de Autorización',''); 
                            $form->input('part1[]','text','','required');     
                        echo '</div>';
                        echo '<div class="large-6 columns">';
                            $form->label('','País de Autorización',''); 
                            $form->select('part1[]','required','');    
                        echo '</div>';
                        echo '<div class="large-6 columns">';
                            $form->label('','Laboratorio Titular',''); 
                            $form->input('part1[]','text','','required');     
                        echo '</div>';
                    echo '</div>';
                    echo '<br>';
                    echo '<div class="row panel">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Dosis',''); 
                            echo '<div class="row">';
                                echo '<div class="large-5 columns">';
                                    $form->input('part1[]','text','','required');    
                                echo '</div>';
                                echo '<div class="large-7 columns">';
                                    $form->select('part1[]','required','');      
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="large-12 columns">';
                            echo '<fieldset><legend>Régimen de Dosificación</legend>';
                                echo '<div class="row">';
                                    echo '<div class="large-6 columns">';
                                        $form->label('','Dosis en Intervalo',''); 
                                        $form->input('part1[]','text','','required'); 
                                    echo '</div>';
                                    echo '<div class="large-6 columns">';
                                        $form->label('','Definición de Intervalo',''); 
                                        echo '<div class="row">';
                                            echo '<div class="large-6 columns">';
                                                $form->input('part1[]','text','','required'); 
                                            echo '</div>';
                                            echo '<div class="large-6 columns">';
                                                $form->select('part1[]','required','');
                                            echo '</div>';                                                                                      
                                        echo '</div>';                                    
                                    echo '</div>';
                                echo '</div>';
                            echo '</fieldset>';    
                        echo '</div>';
                        echo '<div class="large-12 columns">';
                            $form->label('','Comienzo de Administración','');
                            echo '<div class="row">';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','date');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','month');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','year');
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="large-12 columns">';
                            $form->label('','Fin de Administración','');
                            echo '<div class="row">';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','date');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','month');
                                echo '</div>';
                                echo '<div class="large-4 columns">';
                                    $form->select('part1[]','required','year');
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="large-12 columns">';
                            $form->label('','Duración',''); 
                            echo '<div class="row">';
                                echo '<div class="large-5 columns">';
                                    $form->input('part1[]','text','','required');    
                                echo '</div>';
                                echo '<div class="large-5 columns">';
                                    $form->select('part1[]','required','');      
                                echo '</div>';
                                echo '<div class="large-2 columns">';
                                    echo '<button class="button secondary tiny" type="button">Calculadora</button>'; 
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row panel">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Información Adicional','');
                            //textarea($name,$placeholder,$atributo) 
                            $form->textarea('part7[]','','required');
                        echo '</div>';
                    echo '</div>';
                echo '</fieldset>';     
                echo '<fieldset><legend>Relación entre el(los) Medicamentos y la(s) Reaccción(es)</legend>';        
                    echo '<div class="row">';
                        echo '<div class="large-10 columns">';
                            $form->select('part1[]','required',''); 
                        echo '</div>'; 
                        echo '<div class="large-2 columns">';
                            echo '<button class="button alert tiny" type="button">Eliminar</button>'; 
                        echo '</div>';                
                    echo '</div>';
                echo '</fieldset>';
            echo '</fieldset>';
            echo '</div>';
            echo '<div class="large-12 columns content" id="panel8">';
            // Parte 8
            echo '<fieldset><legend>Parte 8 - Evaluación</legend>';
                echo '<fieldset><legend>Evaluación</legend>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Información Adicional','');
                            //textarea($name,$placeholder,$atributo) 
                            $form->textarea('part7[]','','required');
                        echo '</div>'; 
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Comentario del Remitente','');
                            //textarea($name,$placeholder,$atributo) 
                            $form->textarea('part7[]','','required');
                        echo '</div>'; 
                    echo '</div>'; 
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Diagnóstico del Remitente','');
                            echo '<div class="row">';
                                echo '<div class="large-3 columns">';
                                    $form->select('part1[]','required',''); 
                                echo '</div>'; 
                                echo '<div class="large-3 columns">';
                                    $form->select('part1[]','required',''); 
                                echo '</div>'; 
                                echo '<div class="large-2 columns">';
                                    $form->input('part1[]','text','','required');    
                                echo '</div>'; 
                                echo '<div class="large-2 columns">';
                                    $form->select('part1[]','required',''); 
                                echo '</div>'; 
                                echo '<div class="large-2 columns">';
                                    echo '<button class="button secondary tiny" type="button">Buscar</button>'; 
                                echo '</div>'; 
                            echo '</div>';
                        echo '</div>'; 
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="large-12 columns">';
                            $form->label('','Referencias','');
                            //textarea($name,$placeholder,$atributo) 
                            $form->textarea('part7[]','','required');
                        echo '</div>'; 
                    echo '</div>'; 
                echo '</fieldset>';                    
                echo '<button class="button expand radius" type="submit">Guardar Reporte de Reacción Adversa</button>'; 
            echo '</fieldset>';
            echo '</div>';            
            /*
            echo '<div class="large-12 columns content active" id="paneln">';
            // Parte n
            echo '<fieldset><legend>Parte n - (lorem ipsum)</legend>';
            //////////////
            
            
            //////////////
            echo '</fieldset>';
            echo '</div>';
            */
        echo '</div>';

        
    $form->form_F();
    // Fin del Formulario
    //$menu->menu_F(); // Imprime el fin del menu 
    
echo '</div>';
$pie = new Pie();
$html->links('JS','js/foundation/foundation.js');
$html->links('JS','js/foundation/foundation.abide.js');
$html->links('JS','js/jquery.js');
$html->links('JS','js/foundation.min.js');
echo '<script>
      $(document).foundation();
    </script>';
$html->body_F();

?>



